### ISSUE TITLE
How to handle touch on ContentViewController

### ISSUE THREAD

**Issue by zzasdee** [plasmLC/IQSideMenu#7]
When I toggle to Side menu I'm still able to manipulate Content View Controller. How to lock Controller while Side menu is visible? And how to hide Side menu when I touch Content View Controller. Thx

**Comment by plasmLC** [comment]
Hi! To disable touches on contentViewController, you can use it`s view`s .userInteractionEnabled (BOOL) property.
Anyway, i think behaviour you described is incorrect, so i will not support this feature.

What means "hide side menu"? You can use `- (void)toggleMenuAnimated:(BOOL)animated;` method if i correctly catch your question.

**Comment by plasmLC** [comment]
@zzasdee also you should perform update cause i`ve updated lib right now by serious reason (see details in pull requests and commit messages).
